include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

stages:
  - deploy
  - scan

variables:
  PLATFORMS: "linux/amd64,linux/arm64"

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  stage: deploy
  script:
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE},jitesoft/php-fpm,ghcr.io/jitesoft/php-fpm" "${TAGS}")
    - docker buildx build --platform ${PLATFORMS} --progress plain --push ${TAG_LIST} --build-arg PHP_VERSION="${PHP_VERSION}" .
  tags: [ jitesoft, buildx, protected ]

build:8.0:
  <<: *build
  variables:
    PHP_VERSION: "8.0"
    TAGS: "stable,latest,8,8.0"

build:7.4:
  <<: *build
  variables:
    PHP_VERSION: "7.4"
    TAGS: "7,7.4"

build:7.3:
  <<: *build
  variables:
    PHP_VERSION: "7.3"
    TAGS: "7.3"


scan:7.4:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:7.4"

scan:7.3:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:7.3"

