stages:
  - deploy
  - notify

.build: &build
  services:
    - docker:dind
  image: docker:latest
  stage: deploy
  variables:
    EXTRA_TAGS: ""
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - docker pull php:${PHP_VERSION}-fpm-alpine
  script:
    - BUILD=$(docker build --build-arg PHP_VERSION="${PHP_VERSION}" --no-cache -q .)
    - TAGS="${PHP_VERSION} ${EXTRA_TAGS}"
    - for tag in ${TAGS}; do docker tag ${BUILD} jitesoft/php-fpm:${tag}; docker push jitesoft/php-fpm:${tag}; done
  after_script:
      - docker run --rm jitesoft/php-fpm:${PHP_VERSION} php -v

build:7.3:
  <<: *build
  variables:
    PHP_VERSION: "7.3"
    EXTRA_TAGS: "stable latest 7"

build:7.2:
  <<: *build
  variables:
    PHP_VERSION: "7.2"

build:7.1:
  <<: *build
  variables:
    PHP_VERSION: "7.1"

build:7.0:
  <<: *build
  variables:
    PHP_VERSION: "7.0"

build:5.6:
  <<: *build
  variables:
    PHP_VERSION: "5.6"

trigger_build:
  image: alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${NOTIFY_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4048644/trigger/pipeline"
