.build: &build
  image: docker:latest
  stage: deploy
  variables:
    EXTRA_TAGS: ""
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - docker pull php:${PHP_VERSION}-fpm-alpine
  script:
    - BUILD=$(docker build --build-arg PHP_VERSION=${PHP_VERSION} --no-cache -q -f .)
    - TAGS="${PHP_VERSION} ${EXTRA_TAGS}"
    - for tag in ${TAGS; do docker tag {BUILD} jitesoft/php-fpm:${tag}; docker push jitesoft/php-fpm:${tag}; done
  after_script:
      - docker run --rm ${IMG_NAME}:${PHP_VERSION} php -v


build:7.2:
  <<: *build
  variables:
    PHP_VERSION: "7.2"
    EXTRA_TAGS: "latest stable 7"

build:7.1:
  <<: *build
  variables:
    PHP_VERSION: "7.1"

build:7.0:
  <<: *build
  variables:
    PHP_VERSION: "7.0"

build:5.6:
  <<: *build
  variables:
    EXTRA_TAGS: "5"
  variables:
    PHP_VERSION: "5.6"


