include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - deploy
  - scan

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  stage: deploy
  script:
    - docker build --build-arg PHP_VERSION="${PHP_VERSION}" -t ${CI_REGISTRY_IMAGE}:${PHP_VERSION}-tmp .
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${PHP_VERSION}-tmp ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${PHP_VERSION}-tmp jitesoft/php-fpm:${tag}
        docker push jitesoft/php-fpm:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done

build:7.3:
  <<: *build
  variables:
    PHP_VERSION: "7.3"
    TAGS: "stable latest 7 7.3"

build:7.2:
  <<: *build
  variables:
    PHP_VERSION: "7.2"
    TAGS: "7.2"


scan:7.3:
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:7.2"

scan:7.2:
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:7.3"

